#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AwesomeXamarinAndroidRoller.Resource", IsApplication=true)]

namespace AwesomeXamarinAndroidRoller
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040006
			public const int High = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int Low = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Med = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int NotSet = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int colorAccent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int colorPrimary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int colorPrimaryDark = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Rectangle = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int activity_main = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int activity_roller = 2131230726;
			
			// aapt resource value: 0x7f08000a
			public const int btRollDnDefault = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int btRollerAdventurer = 2131230731;
			
			// aapt resource value: 0x7f080007
			public const int grRollerResult = 2131230727;
			
			// aapt resource value: 0x7f080000
			public const int itemGridDescription = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int itemMenuDescription = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int itemMenuTitle = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int lvMenuList = 2131230725;
			
			// aapt resource value: 0x7f080001
			public const int ratingBar = 2131230721;
			
			// aapt resource value: 0x7f080009
			public const int txRollerDescription = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int txRollerDescriptionTile = 2131230728;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ItemGridRoller = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ItemMenuMain = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainActivity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int RollerActivity = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
